name: car_ai_diagnosis
description: تطبيق تشخيص السيارات الذكي بالذكاء الاصطناعي
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.2
  shared_preferences: ^2.5.5
  share_plus: ^13.2.0
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoSansArabic-Regular.ttf
  
