// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKt0dCUFmZRXt50U4KcTY63Oyr0USFrPk',
    appId: '1:674177309544:web:b75f9ff748b1f35750d4dd',
    messagingSenderId: '674177309544',
    projectId: 'smart-car-check-b32aa',
    authDomain: 'smart-car-check-b32aa.firebaseapp.com',
    storageBucket: 'smart-car-check-b32aa.firebasestorage.app',
    measurementId: 'G-DHFD8XWY88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklKKiRRQWZWlIsSOQTOxCXCnF9T8G2aA',
    appId: '1:674177309544:android:46a97938f919083750d4dd',
    messagingSenderId: '674177309544',
    projectId: 'smart-car-check-b32aa',
    storageBucket: 'smart-car-check-b32aa.firebasestorage.app',
  );
}
